### ISSUE TITLE
UnicodeDecodeError

### ISSUE THREAD

**Issue by Autrix** [Devoxin/Lavalink.py#100]
### Summary
On request song/play

### Lavalink & System Version
Linux: ubuntu 18.04
Python: 3.6
Lavalink.py: 3.1.4
Lavalink Player: Build #1186

### Reproduction
- any code will have same results when the video uploader have weird letters in they're name

### Expected Results
- Normal results should pass the video author name

### Actual Results
Thoughts out an error

### Error
UnicodeDecodeError
'utf-8' codec can't decode byte 0xed in position 19: invalid continuation byte

### Where in code is the error
- File: utils.py | @ decode_track at line: 68
![Screenshot_12](https://user-images.githubusercontent.com/47644944/106497257-dab0ea00-64ce-11eb-80f1-b6d9abef8f28.png)

  title = reader.read_utf().decode(errors=decode_errors)
  author = reader.read_utf().decode()
  length = reader.read_long()
  identifier = reader.read_utf().decode()
  is_stream = reader.read_boolean()
  uri = reader.read_utf().decode() if reader.read_boolean() else None
  source = reader.read_utf().decode()

### Checklist
- [x] Have you checked that there aren't other open [Bug Reports](../../issues) for the same problem?
- [x] Have you checked that your Lavalink password isn't visible?
- [x] Have you given a traceback if possible?

**Comment by cdwpx** [comment]
This bug still exists.

Linux: Fedora 36
Python: 1.10.5
Lavalink.py: 3.1.7
Lavalink Player: Build #1257

### Error: 
```
future: <Task finished name='Task-40' coro=<WebSocket.connect() done, defined at /home/cic1e/.local/lib/python3.10/site-packages/lavalink/websocket.py:44> exception=UnicodeDecodeError('utf-8', b'SHOKK\xed\xa0\xbd\xed\xb2\x80', 5, 6, 'invalid continuation byte')>
Traceback (most recent call last):
  File "/home/cic1e/.local/lib/python3.10/site-packages/lavalink/websocket.py", line 108, in connect
    await self._listen()
  File "/home/cic1e/.local/lib/python3.10/site-packages/lavalink/websocket.py", line 121, in _listen
    await self._handle_message(msg.json())
  File "/home/cic1e/.local/lib/python3.10/site-packages/lavalink/websocket.py", line 170, in _handle_message
    await self._handle_event(data)
  File "/home/cic1e/.local/lib/python3.10/site-packages/lavalink/websocket.py", line 194, in _handle_event
    track = decode_track(data['track'])
  File "/home/cic1e/.local/lib/python3.10/site-packages/lavalink/utils.py", line 68, in decode_track
    author = reader.read_utf().decode()
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xed in position 5: invalid continuation byte
```

After some testing it seems to be caused by youtube channels with 2 byte emojis in their name, example video:
<https://www.youtube.com/watch?v=Lz_504h579I>
