### ISSUE TITLE
Can I modify the speed of the track?

### ISSUE THREAD

**Issue by Aayushpatil77** [Devoxin/Lavalink.py#107]

**Comment by sh0tx420** [comment]
no

**Comment by Devoxin** [comment]
You need to be using the 3.2 branch along with a development build of Lavalink. Refer to 3.2 docs on how to use filters, or join the Discord server listed in the README

**Comment by oriapp** [comment]
@Devoxin Are you still maintaining this version?

**Comment by Devoxin** [comment]
Yes, it's the latest version
