### ISSUE TITLE
Use Python's builtin isinstance() instead of this

### ISSUE THREAD

**Issue by Aareon** [Devoxin/Lavalink.py#11]
https://github.com/Devoxin/Lavalink.py/blob/c16ad73e2b1f3a471d1917714869c701c293af96/utils/Utils.py#L11

Rather than creating an all new function for something that is already built in to Python, maybe we should use `isinstance()`

**Comment by Aareon** [comment]
```py
isinstance(num, int)
```
returns True or False

**Comment by Devoxin** [comment]
Fixed in 24c09e7
