### ISSUE TITLE
After i installed dpy 2.0 music doesn't works

### ISSUE THREAD

**Issue by helish88** [Devoxin/Lavalink.py#112]
### Summary

bot join voice channel but music doesn't works
### Lavalink & System Version

discord.py 2.0, ubuntu 18, last version of Lavalink and Lavalink.jar
### Reproduction
![изображение](https://user-images.githubusercontent.com/52331802/128746305-331fbe49-7a20-4936-b2f7-6ec5eb46704f.png)

### Checklist
- [X] Have you checked that there aren't other open [Bug Reports](../../issues) for the same problem?
- [X] Have you checked that your Lavalink password isn't visible?
- [0] Have you given a traceback if possible?

**Comment by oriapp** [comment]
This is not telling me too much, would you mind including error logs and even code (if needed)?

**Comment by helish88** [comment]
no errors, same issue have others who migrated to dpy 2.0, you can install the new version yourself and test

**Comment by helish88** [comment]
btw
```py
pip install -U git+https://github.com/Rapptz/discord.py

**Comment by helish88** [comment]
https://github.com/Rapptz/discord.py/commit/e2250d402e8ad035b2653eb411c8e744cc9eb3bf#diff-c852e7c9bb71098e626976ae25b2c6fc4f6bd67e8e250c853cbd6f3e59df1774L426

**Comment by Hype3808** [comment]
SAME ISSUE.......

**Comment by apex2504** [comment]
you should be able to reimplement `socket_response` yourself with relative ease. use [this](https://github.com/Rapptz/discord.py/blob/462ba84809f43349296c44cbe6468f631a00edab/discord/gateway.py#L419) for reference.

**Comment by Hype3808** [comment]
> you should be able to reimplement `socket_response` yourself with relative ease. use [this](https://github.com/Rapptz/discord.py/blob/462ba84809f43349296c44cbe6468f631a00edab/discord/gateway.py#L419) for reference.

wdym?

**Comment by apex2504** [comment]
> wdym?

i mean that discord.py removed the `socket_response` event which is what lavalink.py requires to forward voice updates to the server. re-implementing this should get your music to work again.

**Comment by Hype3808** [comment]
> > wdym?
> 
> i mean that discord.py removed the `socket_response` event which is what lavalink.py requires to forward voice updates to the server. re-implementing this should get your music to work again.

I ma wait....

**Comment by Devoxin** [comment]
You'll be waiting a while then lol

**Comment by Hype3808** [comment]
> You'll be waiting a while then lol

just dont make me wait until 2022 xD

**Comment by Devoxin** [comment]
Use the new example cog updated for use with Discord.py's voice client.
