### ISSUE TITLE
Certain parts of readthedocs misleading / mising / typoed

### ISSUE THREAD

**Issue by BLovegrove** [Devoxin/Lavalink.py#117]
### Summary
On the readthedocs page for lavalink.py under the [DefaultPlayer section](https://lavalink.readthedocs.io/en/latest/lavalink.html?highlight=defaultplayer#lavalink.DefaultPlayer) the .repeat  definitions states "Whether or not to continuously to play a track.". This sounds like DefaultPlayer.current will seek back to 0 when finished while this bool is True but in fact repeats the whole *queue* when the bool is True. 

Spotted a typo: "Whether or not **to continuously to play** a track" under the DefaultPLayer.repeat section

DefaultPlayer.set_repeat(repeat:bool) is also missing from the documentation as far as ctrl+f / readthedocs search is concerned.

### Checklist
- [x] Have you checked that there aren't other open [Bug Reports](../../issues) for the same problem?

**Comment by BLovegrove** [comment]
To add to this - any chance that single track looping is being implemented already or am I free to write something for the library?

**Comment by Devoxin** [comment]
Seems to be fixed in `3.2`.
