### ISSUE TITLE
aiohttp version update

### ISSUE THREAD

**Issue by ItsMrNatural** [Devoxin/Lavalink.py#119]
Hello, could you please mind updating the required aiohttp version requirements.

Lavalink current aiohttp version requirement: `3.6.0`
Please update it to version `3.7.3` or later

**Comment by ItsMrNatural** [comment]
Let me if I am wrong.

**Comment by waydealphax** [comment]
if it isn't broken, don't fix it. ¯\_(ツ)_/¯

**Comment by ItsMrNatural** [comment]
It is I mean, clashing with other packages which requires newer version of aiohttp.

**Comment by waydealphax** [comment]
what about the people who need an older version of x package, at the end of the day it isnt really going to hurt you that much if you have to run a simple command tbh
