### ISSUE TITLE
Small (but very nice to have) missing type def.

### ISSUE THREAD

**Issue by BLovegrove** [Devoxin/Lavalink.py#131]
### Summary
No typing for DefaultPlayer.node. Would make intellisense a lot better when working with this library.

As I wrote in the title, its a fairly small thing but adding ': lavalink.Node' to the 'self.node = node' line in the  BasePlayer class def would make intellisense a lot more useful when writing song search.... stuff. 

Unrelated but thanks for all your work on the project! Came back to it after a couple years of building my bot with discord.js and its way nicer to use than my last library for Lavalink.
And filters! So glad there's filters now. 

### Lavalink & System Version
Pretty sure this is OS agnostic, but I'm on Ubuntu 22.10, python 3.10.7, Lavalink.py v4.0.4

### Reproduction
Just drop into the default example in vscode with python intellisense enabled and hover over any instance of 'player.node.xyz' 

### Expected Results
any BasePlayer.node to be typed as (at least I assume this is right) lavalink.Node

### Actual Results
No intellisense

### Checklist
- [X] Have you checked that there aren't other open [Bug Reports](../../issues) for the same problem?
- [X] Have you checked that your Lavalink password isn't visible?
- [X] Have you given a traceback if possible?

**Comment by Devoxin** [comment]
Added and published as part of the [4.0.5 update](https://github.com/Devoxin/Lavalink.py/releases/tag/4.0.5).
