### ISSUE TITLE
 Broken playback of some tracks

### ISSUE THREAD

**Issue by shizamuru-dev** [devoxin/Lavalink.py#144]
### Summary
When playing some tracks, playback stops working. By "stops working" I mean the following:

- The track that causes this behavior is not played 
- In case of skipping this track, the following tracks are also not played 

The only solution is to restart the bot, or recreate the player

I would like to point out that a bot written in java(Lavalink-client) using the same server behaves normally

### Lavalink & System Version
The systems where I checked it out: Windows 11(23H2), Debian 11, Ubuntu, Ubuntu server 

Pyhon version: 3.11.2
Lavalink.py version: lates(5.3.0)
Lavalink version version: lates(4.0.4)

### Reproduction
Step 1:
- Create simple music bot ( you can have [this one](https://pastebin.com/RESRBSgP) )
- Add a simple command to skip a track ( you can take [this](https://pastebin.com/wUUcPWpu) )

Step 2:
- Play the track ( you can use [this](https://open.spotify.com/track/3kcfLPHuHgwzRgn5b1O17j) as an example. This problem was first shown to me with it)
- Add 1-2 more tracks of any kind to the queue

Step 3:
- Use the command to skip a track 

### Expected Results
The bot should have played the first track.
After using the command to skip, it should have started playing the second track

### Actual Results
The bot does not play the first track, and even after skipping a track this problem persists

###More info
I found a simple [function to monitor requests](https://pastebin.com/evZKDrQj) and I used it to find out what was causing the behavior. As a result, I saw something unusual: [\*click\*](https://pastebin.com/u5kPELyY)

Pay attention to "position". Unlike normal tracks, which are processed normally, the "position" value is frozen at 460. In case of skipping a track, this value does not change either

### Checklist
- [X] Have you checked that there aren't other open [Bug Reports](../../issues) for the same problem?
- [X] Have you checked that your Lavalink password isn't visible? ( using public server )
- [X] Have you given a traceback if possible?

**Comment by devoxin** [comment]
If the playback freezes then this is an issue with the Lavalink server.

**Comment by devoxin** [comment]
Also this library doesn't use `requests` so that function won't do anything.
