### ISSUE TITLE
Some issues with example music cog

### ISSUE THREAD

**Issue by shikhir-arora** [Devoxin/Lavalink.py#15]
There's an issue here it seems with the `deque` change re: the queue command. I quickly fixed it like this (in the `music.py` example cog):

```py
for i, track in enumerate(player.queue[start:end], start=start): 
```
to:

```py

for i, track in enumerate(list(player.queue)[start:end], start=start): 
```

But I wouldn't say that changing the queue to a list is the most efficient way as it is doing two times the computation and for massive queues it could be slow, but I haven't noticed anything.

It fixes the slice error: `- sequence index must be integer, not 'slice'` on running the queue command.

Also, I don't think shuffle is implemented correctly. It also causes various `- pop() takes no arguments (1 given)` when trying to skip after turning shuffle on/off.

Please excuse any oversights; I'm not the most experienced in Python xD.

**Comment by initzx** [comment]
https://stackoverflow.com/questions/7064289/use-slice-notation-with-collections-deque
islice() should be used instead
