### ISSUE TITLE
Lavalink for async?

### ISSUE THREAD

**Issue by Style77** [Devoxin/Lavalink.py#52]
Is it possible to make lavalink.py working on async? I changed every ctx.send etc. to async version, but now im getting this error:
```  File "C:\Users\Style\Desktop\efira\cogs\music.py", line 52, in play
    results = await self.bot.lavalink.get_tracks(query)
  File "C:\Users\Style\AppData\Local\Programs\Python\Python36-32\lib\site-packages\lavalink\Client.py", line 135, in get_tracks
    return await res.json(content_type=None)
TypeError: json() got an unexpected keyword argument 'content_type'

**Comment by Devoxin** [comment]
Update aiohttp or switch out the function for a custom one that utilises a request lib of your choice.

Additionally, no effort will be made to maintain a version of Lavalink.py for async as usage of the `rewrite` branch is encouraged instead.
