### ISSUE TITLE
Can't load

### ISSUE THREAD

**Issue by DutchAssassin** [Devoxin/Lavalink.py#62]
Hi there,

When trying to load the cog it gives me this error:

`- 'int' object has no attribute 'lavalink'`

**Comment by AndyTempel** [comment]
How does your `__init__` method looks like?

**Comment by DutchAssassin** [comment]
`py
class Music:
    def __init__(self, bot):
        self.bot = bot`

**Comment by DutchAssassin** [comment]
class Music:
    def __init__(self, bot):
        self.bot = bot

**Comment by AndyTempel** [comment]
And where do you define lavalink?

**Comment by DutchAssassin** [comment]
Looks like I don't have that... I used this music.py example 🤷🏻‍♂️

**Comment by Devoxin** [comment]
You're using dev branch cog with Lavalink 2.1.10.

Downgrade your cog, or upgrade your Lavalink.py to V3.

**Comment by DutchAssassin** [comment]
Ah yes. That solved that issue. However I'm having another issue right now... 

It does find music and puts it in the queue, but it doesn't play. When I use the nowplaying command it always stays at 00:00:00...

**Comment by AndyTempel** [comment]
Make sure you execute play method on `TrackEndEvent` event.

**Comment by Zenrac** [comment]
As the original issue has been solved, maybe you should join our support server for further issues : 
https://discord.gg/SbJXU9s

**Comment by AndyTempel** [comment]
I'm going with what @Zenrac said and closing this issue.
