### ISSUE TITLE
Python 3.5.x Compatability

### ISSUE THREAD

**Issue by aikaterna** [Devoxin/Lavalink.py#7]
Could lavalink.py have the two f strings reformatted?

**Comment by martmists** [comment]
Outside of the examples, I don't see any f-strings in the project.

**Comment by aikaterna** [comment]
Once lavalink is installed through pip, f strings can be found in models.py on lines 30, 81 and 148

**Comment by atiwiex** [comment]
I will get pip updated in about 3 hours.

**Comment by atiwiex** [comment]
This can be closed.
