### ISSUE TITLE
Links broke

### ISSUE THREAD

**Issue by Awayyyy** [Devoxin/Lavalink.py#74]
I am currently trying to play music with a youtube link but it doesnt work. Any reason why? Idk

**Comment by Zenrac** [comment]
This issue isn't related to lavalink, I assume it's from your lavaplayer version. Make sure to use lavaplayer > 1.3.19 to prevent some YouTube issues.

**Comment by Devoxin** [comment]
As per what Zenrac said;

While this is not an issue with lavalink.py, you failed to provide any kind of additional information that would help debug this issue.

The first step towards fixing this is to figure out what Lavalink version you're running. You can do this with `java -jar lavalink.jar -v`
Next, identify if your build is out of date. If it is, update your jar.

If the issue persists after updating, join [this Discord server](https://discord.gg/GtHjrmf).
