### ISSUE TITLE
Constant spam of 'Disconnected with code None and reason None' in console

### ISSUE THREAD

**Issue by QuirijnLangedijk** [Devoxin/Lavalink.py#84]
Every +- 30 seconds the following error keeps getting spammed into my console, even when its not playing music:

[NODE-eu-clerq-<URL>:80] Disconnected with code None and reason None
Unable to move players, no available nodes! Waiting for a node to become available.

Any way to supress/fix this error?

**Comment by Devoxin** [comment]
Fix your node.

On a more serious note, this shouldn't be happening but I'm inclined to believe it's an issue with your setup. Can you [join the Discord server](https://discord.gg/SbJXU9s) for further support?

**Comment by NeviraOwner** [comment]
```py
import sys

class DevNull:
    def write(self, msg):
        pass

sys.stderr = DevNull()
```
should suppress all errors, including the ones you're getting

**Comment by Devoxin** [comment]
This a 1 year old issue. Also I highly advise you don't do that, and actually configure via the `logging` module directly.
