### ISSUE TITLE
typo in link

### ISSUE THREAD

**Issue by ItzN00bPvP** [Devoxin/Lavalink.py#94]
### Summary
typo in link at https://lavalink.readthedocs.io/en/latest/quickstart.html
example cog refers to https://github.cmo/Devoxin/Lavalink.py/blob/master/examples/music.py

### Lavalink & System Version
not relevant

### Reproduction
goto https://lavalink.readthedocs.io/en/latest/quickstart.html and click at example cog

### Expected Results
https://github.com/Devoxin/Lavalink.py/blob/master/examples/music.py

### Actual Results
https://github.cmo/Devoxin/Lavalink.py/blob/master/examples/music.py

### Checklist
- [x ] Have you checked that there aren't other open [Bug Reports](../../issues) for the same problem?
- [ ] Have you checked that your Lavalink password isn't visible?
- [ ] Have you given a traceback if possible?

**Comment by AndyTempel** [comment]
This looks like it has already been fixed. 
https://github.com/Devoxin/Lavalink.py/blob/master/docs/quickstart.rst#L15

Maybe @Devoxin just needs to force RTD to update.

**Comment by DMNight6** [comment]
Alright
