### ISSUE TITLE
Add set_repeat

### ISSUE THREAD

**Issue by DMNight6** [Devoxin/Lavalink.py#95]
There is no such thing as set_repeat. I need this to fully complete my bot music.py

**Comment by Taarek** [comment]
Latest version includes both set_repeat and set_shuffle (3.1.2)

**Comment by DMNight6** [comment]
Alright

**Comment by DMNight6** [comment]
object NoneType can't be used in 'await' expression

**Comment by DMNight6** [comment]
it works but I need to hide that issue

**Comment by mouncg** [comment]
@DMNight6 Import contextlib's supress and supress the exception.

**Comment by Devoxin** [comment]
Suppressing exceptions is generally poor practice. I discourage doing so as it can be counter-productive to solving issues in the future.

@DMNight6 your issue stems from the fact you're trying to call `await` on a function that doesn't exist. If you want to make use of `set_repeat`, I advise you clone the dev branch and install that (`pip install git+https://github.com/devoxin/lavalink.py@dev`).

If you don't fancy your chances using a development build, you can do `player.repeat = <bool>` in the meanwhile. I will make a release when I find the time.

Lastly, I shall close this issue as this feature already exists within the `development` branch.

**Comment by DMNight6** [comment]
Ok
