### ISSUE TITLE
Version issue?

### ISSUE THREAD

**Issue by justanothernoob4648** [Devoxin/Lavalink.py#97]
java.lang.UnsupportedClassVersionError: lavalink/server/info/AppInfo has been compiled by a more recent version of the Java Runtime (class file version 55.0), this version of the Java Runtime only recognizes class file versions up to 52.0
I just downloaded the lastest version of Java and this is the error I get when running the java -jar command in terminal

**Comment by Devoxin** [comment]
This is not a lavalink.py issue. Also please use the issue template next time. It exists for a reason.
