### ISSUE TITLE
After loading Lavalink.jar, it plays the every first song that we pass in and stops working after that

### ISSUE THREAD

**Issue by SohamGhugare** [Devoxin/Lavalink.py#98]
### Summary

After we run the Lavalink.jar file, it establishes connection, after that whenever we play very first song, it plays nicely, but if we disconnect the bot after that and try to play another song, it doesnt work. 

### Reproduction
This is the where the jar file gets stuck at (in the terminal)
Loaded playlist Search results for: bekhayali
2020-11-13 12:23:28.786  INFO 34228 --- [   XNIO-1 I/O-4] lavalink.server.io.SocketServer          : {"op": "play", "guildId": "760517589100527656", "track": "QAAAxgIAZEJla2hheWFsaSBGdWxsIFNvbmcgfCBLYWJpciBTaW5naCB8IFNoYWhpZCBLLEtpYXJhIEF8U2FuZGVlcCBSZWRkeSBWYW5nYSB8IFNhY2hldC1QYXJhbXBhcmEgfCBJcnNoYWQACFQtU2VyaWVzAAAAAAAFZtAAC1ZPTEtKSnZmQWJnAAEAK2h0dHBzOi8vd3d3LnlvdXR1YmUuY29tL3dhdGNoP3Y9Vk9MS0pKdmZBYmcAB3lvdXR1YmUAAAAAAAAAAA=="}

### Expected Results

The current song will stop when it disconnects.

### Actual Results

The previous song never stops. If we disconnect the bot from the vc, and reconnect it, the bots seems to be playing something but nothing is audible

### Checklist
- [x] Have you checked that there aren't other open [Bug Reports](../../issues) for the same problem?
- [x] Have you checked that your Lavalink password isn't visible?
- [x] Have you given a traceback if possible?

**Comment by Alvaro11143** [comment]
This seems to be a problem with your code handling disconnect events, see the example cog here: https://github.com/Devoxin/Lavalink.py/blob/master/examples/music.py

**Comment by SohamGhugare** [comment]
Oh yes! I figured it out, if we don't clear the queue before disconnecting the bot, it lags out the playlist queue, leading to the issue I mentioned above.
